In [1]:
import pandas as pd
import numpy as np

In [2]:
# Numeros con dos cifras decimales
pd.options.display.float_format='{:.2f}'.format
np.set_printoptions(precision=2)

In [7]:
x1 = np.random.rand(2, 5) * 10
x1

array([[1.66, 0.36, 6.57, 1.79, 5.62],
       [9.35, 6.34, 4.71, 0.4 , 7.82]])

In [5]:
x2 = np.random.rand(2, 5) * -1
x2

array([[-0.83, -0.87, -0.81, -0.65, -0.33],
       [-0.51, -0.21, -0.55, -0.99, -0.05]])

In [9]:
np.concatenate([x1, x2]), np.concatenate([x1, x2]).shape

(array([[ 1.66,  0.36,  6.57,  1.79,  5.62],
        [ 9.35,  6.34,  4.71,  0.4 ,  7.82],
        [-0.83, -0.87, -0.81, -0.65, -0.33],
        [-0.51, -0.21, -0.55, -0.99, -0.05]]), (4, 5))

In [10]:
np.concatenate([x1, x2], axis=1), np.concatenate([x1, x2], axis=1).shape

(array([[ 1.66,  0.36,  6.57,  1.79,  5.62, -0.83, -0.87, -0.81, -0.65,
         -0.33],
        [ 9.35,  6.34,  4.71,  0.4 ,  7.82, -0.51, -0.21, -0.55, -0.99,
         -0.05]]), (2, 10))

In [11]:
s1 = pd.Series(x1[0], index=['a', 'b', 'c', 'd', 'e'])
s1

a   1.66
b   0.36
c   6.57
d   1.79
e   5.62
dtype: float64

In [13]:
s2 = pd.Series(x2[0], index=['c', 'd', 'e', 'f', 'g'])
s2

c   -0.83
d   -0.87
e   -0.81
f   -0.65
g   -0.33
dtype: float64

In [14]:
pd.concat([s1, s2])

a    1.66
b    0.36
c    6.57
d    1.79
e    5.62
c   -0.83
d   -0.87
e   -0.81
f   -0.65
g   -0.33
dtype: float64

In [15]:
pd.concat([s1, s2], axis=1)

0     1
a 1.66   nan
b 0.36   nan
c 6.57 -0.83
d 1.79 -0.87
e 5.62 -0.81
f  nan -0.65
g  nan -0.33

In [16]:
# borrar el indice de una serie
s1.reset_index(drop=True)

0   1.66
1   0.36
2   6.57
3   1.79
4   5.62
dtype: float64

In [17]:
pd.concat([s1.reset_index(drop=True), s2.reset_index(drop=True)], axis=1)

0     1
0 1.66 -0.83
1 0.36 -0.87
2 6.57 -0.81
3 1.79 -0.65
4 5.62 -0.33

In [19]:
df1 = pd.DataFrame(np.random.rand(3, 2)*10, columns= ['a', 'b'])
df1

a    b
0 6.68 5.14
1 0.92 7.58
2 5.70 9.02

In [20]:
df2 = pd.DataFrame(np.random.rand(3, 2)*-1, columns= ['a', 'b'], index=[2, 3, 4])
df2

a     b
2 -0.12 -0.06
3 -0.38 -0.95
4 -0.55 -0.10

In [21]:
pd.concat([df1, df2])

a     b
0  6.68  5.14
1  0.92  7.58
2  5.70  9.02
2 -0.12 -0.06
3 -0.38 -0.95
4 -0.55 -0.10

In [22]:
pd.concat([df1, df2], axis = 1)

a    b     a     b
0 6.68 5.14   nan   nan
1 0.92 7.58   nan   nan
2 5.70 9.02 -0.12 -0.06
3  nan  nan -0.38 -0.95
4  nan  nan -0.55 -0.10

In [23]:
pd.concat([df1, df2], axis = 1, join='inner')

a    b     a     b
2 5.70 9.02 -0.12 -0.06

In [24]:
pd.concat([df1.reset_index(drop=True), df2.reset_index(drop=True)], axis = 1)

a    b     a     b
0 6.68 5.14 -0.12 -0.06
1 0.92 7.58 -0.38 -0.95
2 5.70 9.02 -0.55 -0.10

In [26]:
df1.append(df2).append(df1)

a     b
0  6.68  5.14
1  0.92  7.58
2  5.70  9.02
2 -0.12 -0.06
3 -0.38 -0.95
4 -0.55 -0.10
0  6.68  5.14
1  0.92  7.58
2  5.70  9.02

In [27]:
# Transpuesta
df1.T

0    1    2
a 6.68 0.92 5.70
b 5.14 7.58 9.02

In [28]:
df1.T.append(df2.T).T

a    b     a     b
0 6.68 5.14   nan   nan
1 0.92 7.58   nan   nan
2 5.70 9.02 -0.12 -0.06
3  nan  nan -0.38 -0.95
4  nan  nan -0.55 -0.10